pipeline {
    agent any

    environment {
        NODEJS_HOME = tool 'nodejs' // Assuming you have configured a Node.js tool in Jenkins
    }

    stages {
        stage('Preparation') {
            steps {
                script {
                    checkout scm
                    sh "git rev-parse --short HEAD > .git/commit-id"
                    commit_id = readFile('.git/commit-id').trim()
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    nodejs(nodeJSInstallationName: 'nodejs') {
                        sh 'npm install --only=dev'
                        sh 'npm test'
                    }
                }
            }
        }

        stage('Docker Build/Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v2/', 'dockerhub') {
                        def app = docker.build("srisairaaj10/docker-demo:${commit_id}", '.').push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build or deployment failed!'
            // You can add additional error handling or notification steps here
        }
    }
}
